### ISSUE TITLE
Can't save changes to settings

### ISSUE THREAD

**Issue by rbdone** [denis-zhdanov/intellij-plugin-copy-on-steroids#1]
Just tried the "'Copy' on Steroids" plugin you made.  I love being able to copy the formatting (have wanted to do this for a while).

There appears to be a bug with the plugin where I can't save the settings.  To duplicate, do the following:
1. Install 'Copy' on Steroids.
2. Look at the plugin preferences and notice that it "Use colors of scheme" has "Active scheme" selected.
3. Switch scheme to something different.

Expected: "Apply" button should be enabled.
Actual: "Apply" button remains disabled and is not clickable.  Clicking "OK" does not save the setting.

System:
Mac OS X 10.7.5
IntelliJ IDEA 12.0.4
Build #IU-123.169
JDK: 1.6.0_43

**Comment by denis-zhdanov** [comment]
Fixed. New plugin version (2.1) is published
